In [2]:
##Librerias 
import numpy as np
import matplotlib.pyplot as plt
import math
import scipy as sp

In [3]:
##Exportación de los datos 
darray = np.genfromtxt('accel.txt',delimiter=" ",missing_values=np.nan)
darray

array([[0.        , 0.        ],
       [0.11      , 0.20957038],
       [0.22      , 0.44218515],
       [0.33      , 0.65573128],
       [0.44      , 0.87299237],
       [0.55      , 1.08133683],
       [0.66      , 1.28101362],
       [0.77      , 1.55836773],
       [0.88      , 1.72473922],
       [0.99      , 1.9338318 ],
       [1.1       , 2.22924501],
       [1.21666667, 2.19410295],
       [1.33333333, 2.22785879],
       [1.45      , 2.19854377],
       [1.56666667, 2.2520631 ],
       [1.68333333, 2.2581766 ],
       [1.8       , 2.25699586],
       [1.9       , 1.9151173 ],
       [2.        , 1.66995246],
       [2.1       , 1.3671418 ],
       [2.2       , 1.10986788],
       [2.3       , 0.8213284 ],
       [2.4       , 0.54823411],
       [2.5       , 0.27934386],
       [2.6       , 0.        ]])

In [4]:
t = darray[:,0]
a = darray[:,1]
t

array([0.        , 0.11      , 0.22      , 0.33      , 0.44      ,
       0.55      , 0.66      , 0.77      , 0.88      , 0.99      ,
       1.1       , 1.21666667, 1.33333333, 1.45      , 1.56666667,
       1.68333333, 1.8       , 1.9       , 2.        , 2.1       ,
       2.2       , 2.3       , 2.4       , 2.5       , 2.6       ])

In [14]:
def simpson(f,t):
    n = len(t)
    int1 = 0
    int2 = 0
    delta = (t[-1]-t[0])/n
    
    for k in range((n+1)/2):
        int1 += f[2*k-1]
    for i in range((n+1)/2-1):
        int2 += f[2*k]
        
    integral = (delta/3)*(f[0]+4*int1+2*int2+f[n])
    return integral 

In [15]:
V = np.zeros(len(t))
for i in range(1,len(t)):
    V[i-1] = simpson(a[0:i],t[0:i])
    

    

IndexError: index 1 is out of bounds for axis 0 with size 1

In [11]:
a[0:2]

array([0.        , 0.20957038])

In [16]:
len(a)

25